<?php

namespace App\Livewire\Admin;

use Livewire\Attributes\Layout;
use Livewire\Component;

class Roadmap extends Component
{
    public $phases = [
        [
            'id' => 1,
            'title' => 'Fase 1: Fundação & Max Performance (Blade + Alpine)',
            'status' => 'Concluído',
            'progress' => 100,
            'color' => 'green',
            'description' => 'Construção da arquitetura base do sistema com foco em velocidade extrema. Migramos do Livewire pesado para uma arquitetura híbrida de Blade Templates com Alpine.js, resultando em carregamentos instantâneos e menor consumo de recursos no servidor.',
            'technical_details' => [
                'Stack' => 'Laravel 11, Blade, Alpine.js, Tailwind CSS, Vite',
                'Performance' => 'Eliminação de Round-trips desnecessários do Livewire',
                'Arquitetura' => 'Multi-Tenant por Empresa com isolamento total de dados',
                'Frontend' => 'Layout unificado "Dashboard-First" em Blade',
                'Segurança' => 'Spatie Permission e Proteção de API via Middleware Auth',
            ],
            'tasks' => [
                'Setup Core Laravel 11' => 'OK',
                'Migração Blade + Alpine' => 'OK',
                'Layout Unificado Dark Mode' => 'OK',
                'Autenticação Custom (Simple Login)' => 'OK',
                'API REST para Front-end' => 'OK',
                'Multi-Tenant por Empresa' => 'OK',
            ],
        ],
        [
            'id' => 2,
            'title' => 'Fase 2: Motor de Produtos, Estoque & Hub Fiscal',
            'status' => 'Concluído',
            'progress' => 100,
            'color' => 'green',
            'description' => 'Desenvolvimento do Master Data e Identidade Fiscal. Inclui o motor de comunicação com a Sefaz para recebimento automático de NF-e e o WMS multi-estoque, tudo operando sobre a nova camada de performance Alpine.js.',
            'technical_details' => [
                'Hub Fiscal' => 'Integração Sefaz via distDFe (Busca por NSU)',
                'Geração DANFE' => 'PDF de DANFE A4 e Simplificada integrados ao layout',
                'WMS Multiestoque' => 'Gestão de múltiplos armazéns (Físico, Full, Virtual)',
                'Produtos' => 'Cadastro completo com suporte a Variações e Kits/Compostos',
                'Automação' => 'Baixa automática de estoque por canal de venda',
            ],
            'tasks' => [
                'WebService Sefaz (Recebimento)' => 'OK',
                'Importação XML Assíncrona' => 'OK',
                'Cadastro de SKUs e Variações' => 'OK',
                'Transferência entre Depósitos' => 'OK',
                'Baixa Automática por Pedido' => 'OK',
                'Dashboard de Estoque (Alpine)' => 'OK',
            ],
        ],
        [
            'id' => 3,
            'title' => 'Fase 3: Marketplace Sync & Integrações',
            'status' => 'Concluído',
            'progress' => 95,
            'color' => 'green',
            'description' => 'Integração via API REST com os principais canais de venda. O foco é a sincronização de estoque centralizado, gestão de anúncios e conexão via OAuth com os marketplaces.',
            'technical_details' => [
                'ARQUITETURA GERAL' => 'Integrações salvas na tabela "integracoes" com campos: access_token, refresh_token, client_id, client_secret, empresa_id, marketplace, ativo',
                'OAuth Flow' => 'Redirect URL: /auth/callback para ML, /notification/callback para Bling',
                
                '=== MERCADO LIVRE ===' => '',
                'OAuth URL' => 'https://auth.mercadolivre.com.br/authorization?response_type=code&client_id={APP_ID}',
                'Token URL' => 'https://api.mercadolibre.com/oauth/token',
                'Anúncios API' => 'GET /users/{USER_ID}/items/search → loop de 100 em 100 → GET /items/{ITEM_ID}',
                'ANÚNCIOS (MLBU/MLB)' => 'Busca direta da API /items/{id} com cache de 5 minutos. Retorna: titulo, price, available_quantity, status, pictures, attributes (EAN, NCM, brand, dimensions), variations, seller_custom_field (SKU), shipping (mode, logistic_type, free_shipping), listing_type_id',
                'Shipment API' => 'GET /shipments/{SHIPMENT_ID} - retorna custo_frete real, dimensions, status',
                'Frete Calculation' => 'Tiers por peso: 0-500g=R$7.79, 500g-1kg=R$9.49, 1-2kg=R$10.79, 2-5kg=R$17.49, 5-10kg=R$24.90, 10-15kg=R$44.90, 15-20kg=R$54.90, 20-25kg=R$64.90',
                'Frete FULL' => 'Tipo de envio full_variation (desconto no Marketplace fee)',
                'Frete FLEX' => 'Entrega no mesmo dia/c.next (custo: tableLucro[frete])',
                'Frete SOURCE' => 'Campo freight_source no DB: shipment_api (real), calculated (estimado), free, manual',
                'Repricer' => 'Comando RunRepricer.php - roda a cada 3h via cron, ajusta preços baseado em custo + margens',
                'Webhooks ML' => 'POST /webhooks/meli - processa orders, shipments, payments, listings',
                'Flex Alerts' => 'Corte 7h e 12h - notifica se há Flex para entregar',
                'ML Marketplace ID' => 'Brazil=MLB (MLB-55-52511006)',
                
                '=== BLING (ERP) ===' => '',
                'OAuth URL' => 'https://www.bling.com.br/Api/v3/oauth/authorize?response_type=code&client_id={CLIENT_ID}',
                'Token URL' => 'https://www.bling.com.br/Api/v3/oauth/token',
                'Produtos API' => 'GET /produtos - sincroniza produtos com SKU mapping',
                'Pedidos API' => 'GET /pedidos - sincroniza pedidos',
                'Contato Teste' => 'GET /contatos - usa para testar conexão (não tem /me)',
                'Webhook Bling' => 'POST /integrations/bling/notification/callback - notifications de pedidos',
                
                '=== AMAZON (SP-API) ===' => '',
                'AWS Login' => 'Login with Amazon (LWA) para получить access_token',
                'SP-API' => 'Selling Partner API com marketplace A2Q3Y263D00KWC (Brasil)',
                'Orders API' => 'GET /orders/v0/orders - sincroniza pedidos',
                'Inventário API' => 'POST /listings/2021-08-01/items - atualiza estoque',
                'Marketplace BR' => 'A2Q3Y263D00KWC',
                
                '=== TABELAS DO BANCO ===' => '',
                'marketplace_anuncios' => 'id, empresa_id, integracao_id, product_sku_id, marketplace, external_id, sku, titulo, preco, estoque, status, json_data, freight_custo_seller, freight_source, freight_type, created_at, updated_at',
                'marketplace_pedidos' => 'id, empresa_id, integracao_id, marketplace, external_id, status, valor_total, freight_custo, freight_type, created_at',
                'product_sku_id FK' => 'Relacionamento: marketplace_anuncios.product_sku_id → product_skus.id',
            ],
            'tasks' => [
                'Criação da Tabela de Integrações' => 'OK',
                'Módulo de Gestão de Contas Marketplace' => 'OK',
                'Setup OAuth Mercado Livre' => 'OK',
                'Sincronizador de Anúncios ML (API real-time, cache 5min)' => 'OK',
                'Sincronizador de Pedidos ML' => 'OK',
                'Frete ML (FULL/FLEX calculation via shipment API)' => 'OK',
                'Repricer (auto price adjustment)' => 'OK',
                'Setup OAuth Bling' => 'OK',
                'Sincronizador de Produtos Bling' => 'OK',
                'Sincronizador de Pedidos Bling' => 'OK',
                'Setup OAuth Amazon (SP-API)' => 'OK',
                'Sincronizador de Pedidos Amazon' => 'OK',
                'Sincronizador de Inventário Amazon' => 'OK',
                'Importação NFes Marketplace' => 'OK',
                'Monitor de Tarefas' => 'OK',
                'DRE - Demonstração de Resultados' => 'OK',
                'Cadastro de Despesas' => 'OK',
                'Gestão de Parceiros' => 'OK',
                'Ferramenta ZPL' => 'OK',
                'Ferramenta EAN/Barcode' => 'OK',
                'Dashboard Financeiro' => 'OK',
                'Webhook Notifications ML' => 'OK',
                'Alertas de Frete (Flex/Full)' => 'OK',
            ],
        ],
        [
            'id' => 4,
            'title' => 'Fase 4: Financial Intelligence & Ads ROI',
            'status' => 'Em Andamento',
            'progress' => 60,
            'color' => 'amber',
            'description' => 'O cérebro estratégico do sistema. Dashboard em tempo real com métricas de vendas, lucratividade por marketplace e preparação para integração com APIs de advertising.',
            'technical_details' => [
                'CÁLCULO DE MARGEM' => '',
                'Fórmula' => 'lucro_bruto = preco - custo - valorTaxas - frete - imposto',
                'Custo' => ' marketplace_anuncio.productSku.product.preco_custo (do produto vinculado)',
                'Taxas ML' => 'getTaxasEstimadas() - Gold Special: 16.5%, Premium: 12%, Clássico: 8%',
                'Imposto' => 'preco * 0.10 (10% Simples Nacional)',
                'Frete' => 'Se freight_source=shipment_api: usa freight_custo_seller real. Se calculated: usa tier baseado no peso.',
                'Margem' => '(lucro_bruto / preco) * 100. Verde se > 0, vermelho se < 0.',
                
                'TABELAS RELACIONADAS' => '',
                'products' => 'id, empresa_id, nome, preco_venda, preco_custo, estoque, foto_principal',
                'product_skus' => 'id, product_id, sku, preco_venda, preco_custo, estoque, gtin, ncm',
                'marketplace_anuncios' => 'product_sku_id FK para product_skus',
                'marketplace_pedidos' => 'freight_custo, freight_type (full/flex), status',
                
                'DASHBOARDS' => '',
                'Orders Index' => 'Cards view e Table view com breakdown: Taxa, Frete, Imposto, Custo, Lucro',
                'Vendas por Hora' => 'Gráfico em tempo real',
                'Comparativo Semanal' => 'Vendas últimos 7 dias vs semana anterior',
            ],
            'tasks' => [
                'Dashboard Principal com Vendas do Dia' => 'OK',
                'Vendas em Tempo Real' => 'OK',
                'Dashboard de Lucratividade' => 'OK',
                'Dashboard por Marketplace' => 'OK',
                'Comparativo Semanal de Vendas' => 'OK',
                'Orders - Cards/Table Views' => 'OK',
                'Cálculo de Margem com Custo' => 'OK',
                'Frete Real do Shipment ML' => 'OK',
                'Taxa ML (16.5% gold_special)' => 'OK',
                'Imposto Simples (10%)' => 'OK',
                'Reprocessar Frete Pedidos (432 atualizados)' => 'OK',
                'Vincular Anúncio ao Produto (product_sku_id)' => 'OK',
                'Monitor de ROI de Ads' => 'Pendente',
                'Alerta de Margem Negativa' => 'Pendente',
                'Relatório Contábil Consolidado' => 'Pendente',
            ],
        ],
        [
            'id' => 5,
            'title' => 'Fase 5: SAC Eliot ⚡ (Atendimento Proativo)',
            'status' => 'Pendente',
            'progress' => 0,
            'color' => 'emerald',
            'description' => 'Central de mensagens unificada com inteligência artificial para aumentar conversão e reduzir reclamações.',
            'technical_details' => [
                'IA Atendimento' => 'Eliot usa Gemini IA para responder perguntas baseadas na descrição técnica e estoque',
                'Sentimento' => 'Análise automática de mensagens para priorizar clientes insatisfeitos',
                'Automação' => 'Mensagens automáticas de pós-venda (rastreio, agradecimento, pedido de review)',
                'Base de Conhecimento' => 'Wiki centralizada para respostas rápidas e consistentes',
                'OpenClaw Integration' => 'Agente rodando no gateway com acesso a tools',
                'Mensagens Motivacionais' => 'Daily messages para Luciana (Boletim Seduc)',
            ],
            'tasks' => [
                'Central Unificada de SAC' => 'Pendente',
                'Engine Eliot Automation' => 'Pendente',
                'Pós-venda Automatizado' => 'Pendente',
                'Dashboard de NPS e Conversão' => 'Pendente',
            ],
        ],
    ];

    #[Layout('components.layouts.app')]
    public function render()
    {
        return view('livewire.admin.roadmap');
    }
}
